# Generated by Django 4.0.4 on 2022-05-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_alter_event_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='gamers', to='levelupapi.gamer'),
        ),
    ]
